// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-JtQLf_Enm7lyrgL90QBT4GBU57Ak8Nk',
    appId: '1:1056554286654:web:54b06afa5ef3ad20ee9b6f',
    messagingSenderId: '1056554286654',
    projectId: 'device-streaming-7ab87962',
    authDomain: 'device-streaming-7ab87962.firebaseapp.com',
    storageBucket: 'device-streaming-7ab87962.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAmVko8OiO3yvab19xcmP_iJpwklMkaTo',
    appId: '1:1056554286654:android:0792cc29310fc96eee9b6f',
    messagingSenderId: '1056554286654',
    projectId: 'device-streaming-7ab87962',
    storageBucket: 'device-streaming-7ab87962.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1V3SQp7KnFc610lof2DxKpAcyQUqCy3U',
    appId: '1:1056554286654:ios:d563cffe1055b224ee9b6f',
    messagingSenderId: '1056554286654',
    projectId: 'device-streaming-7ab87962',
    storageBucket: 'device-streaming-7ab87962.firebasestorage.app',
    iosBundleId: 'com.example.twodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1V3SQp7KnFc610lof2DxKpAcyQUqCy3U',
    appId: '1:1056554286654:ios:d563cffe1055b224ee9b6f',
    messagingSenderId: '1056554286654',
    projectId: 'device-streaming-7ab87962',
    storageBucket: 'device-streaming-7ab87962.firebasestorage.app',
    iosBundleId: 'com.example.twodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-JtQLf_Enm7lyrgL90QBT4GBU57Ak8Nk',
    appId: '1:1056554286654:web:7f9ba9edb7c90f8dee9b6f',
    messagingSenderId: '1056554286654',
    projectId: 'device-streaming-7ab87962',
    authDomain: 'device-streaming-7ab87962.firebaseapp.com',
    storageBucket: 'device-streaming-7ab87962.firebasestorage.app',
  );
}
